# Generated by Django 4.2.10 on 2024-02-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_payment', '0001_initial'),
        ('App_order', '0002_rename_updated_order_update_remove_cart_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_payment.checkout'),
        ),
    ]
