# Generated by Django 4.2.10 on 2024-02-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0003_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('SSL Commerz', 'SSL Commerz')], max_length=100, null=True),
        ),
    ]
