# Generated by Django 4.2.11 on 2024-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_order', '0004_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('SSL Commerzs', 'SSL Commerzs')], max_length=100, null=True),
        ),
    ]
